### PR TITLE
fixing use of path.resolve, issue #118, all tests pass

### PR DESCRIPTION
**Pull request by rlamorea**
https://github.com/dylang/grunt-notify/issues/118

### CODE REVIEW

**Comment by rquadling** [comment]
Should also fix #120

**Comment by dylang** [comment]
Thanks for doing this!

**Comment by ba55ie** [comment]
And should fix #116

**Comment by vchinthakunta** [comment]
@rlamorea @dylang @ba55ie  Thanks for putting this up. I had the same issue, needed to update my toaster manually even though I am using grunt-notify: 0.4.5. Doesn't 0.4.5 expect to have changes from 0.4.3?

**Pull request merged**
